import { motion } from 'framer-motion';

const coreTech = [
  'TypeScript', 'React / Next.js', 'Laravel', 'Tailwind CSS',
  'Framer Motion', 'Node.js', 'MySQL', 'Web A11y',
];

const staggerVariants = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.08 } },
};

const fadeUp = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: [0.76, 0, 0.24, 1] } },
};

export default function Manifesto() {
  return (
    <section
      id="manifesto"
      aria-label="Manifesto"
      className="bg-brutal-black text-white border-y-4 border-brutal-black"
    >
      <div className="max-w-[1280px] mx-auto px-6 py-20 sm:py-28">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="flex items-center gap-4 mb-12 sm:mb-16"
        >
          <span className="font-sans text-xs font-black tracking-[0.2em] text-brutal-pink">02</span>
          <h2 className="font-display text-5xl sm:text-7xl md:text-8xl uppercase tracking-tight text-brutal-yellow leading-none">
            The Manifesto
          </h2>
          <div className="flex-1 border-t-4 border-white/20" />
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 sm:gap-16">
          {/* Left: Text */}
          <motion.div
            variants={staggerVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            className="space-y-8 text-lg sm:text-xl leading-relaxed font-sans font-medium text-white/80"
          >
            <motion.p variants={fadeUp}>
              The web has become a sea of sameness. Soft gradients, rounded corners,
              and predictable layouts generated by machines, for machines.
            </motion.p>
            <motion.p variants={fadeUp}>
              I believe in{' '}
              <strong className="bg-brutal-yellow text-brutal-black px-2 border-2 border-transparent font-black">
                structural integrity
              </strong>{' '}
              over superficial polish. A website is a tool, not a painting.
              Every pixel should earn its place.
            </motion.p>
            <motion.p variants={fadeUp}>
              My code is semantic, my performance budgets are strict, and my designs
              are engineered to demand attention — not beg for it.
            </motion.p>
            <motion.p
              variants={fadeUp}
              className="font-display text-3xl sm:text-4xl uppercase text-brutal-yellow leading-tight pt-4"
            >
              No templates. No trends. Just engineering.
            </motion.p>
          </motion.div>

          {/* Right: Stack + Stats */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            {/* Core Stack */}
            <h3 className="font-display text-3xl sm:text-4xl uppercase text-white border-b-4 border-white pb-3 mb-6">
              Core Stack
            </h3>
            <div className="flex flex-wrap gap-3">
              {coreTech.map((tech, i) => (
                <span
                  key={i}
                  className="px-5 py-3 border-2 border-brutal-yellow text-brutal-yellow font-sans font-bold text-base sm:text-lg uppercase hover:bg-brutal-yellow hover:text-brutal-black transition-colors duration-200 cursor-default"
                >
                  {tech}
                </span>
              ))}
            </div>

            {/* Stats */}
            <div className="mt-10 grid grid-cols-2 gap-4 sm:gap-6">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: 0.3 }}
                className="border-2 border-white/20 p-4 sm:p-5"
              >
                <p className="font-display text-4xl sm:text-5xl text-brutal-yellow">5+</p>
                <p className="font-sans text-xs font-bold uppercase text-white/50 tracking-wider mt-1">
                  Years Building
                </p>
              </motion.div>
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: 0.4 }}
                className="border-2 border-white/20 p-4 sm:p-5"
              >
                <p className="font-display text-4xl sm:text-5xl text-brutal-yellow">20+</p>
                <p className="font-sans text-xs font-bold uppercase text-white/50 tracking-wider mt-1">
                  Projects Shipped
                </p>
              </motion.div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
